FROM python:3

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

RUN pip install pytest pytest-cov SQLAlchemy psycopg2-binary

WORKDIR /app
COPY . /app

RUN pytest --setup-show tests/ -v -s --cov=.

FROM python:3

RUN pip install SQLAlchemy psycopg2-binary

WORKDIR /app
COPY . /app

ENTRYPOINT ["python","/app/main.py"]
